config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'recipes#index'
  
  resources :recipes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  before_action :set_recipe, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @recipes = Recipe.all
  end

  def show
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    if @recipe.save
      redirect_to @recipe, notice: "Recipe successfully created!"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @recipe.update(recipe_params)
      redirect_to @recipe, notice: "Recipe successfully updated!"
    else
      render :edit
    end
  end

  def destroy
    @recipe.destroy
    redirect_to recipes_url, notice: 'Recipe successfully deleted.'
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :ingredients, :instructions, :source_url)
  end

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(flash_type)
    {
      success: 'alert-success',
      error: 'alert-danger',
      alert: 'alert-warning',
      notice: 'alert-info'
      # not sure what next line is doing
    }.stringify_keys[flash_type.to_s] || flash_type.to_s
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipes</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flash' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/recipes/_form.html.erb
<%= form_with model: @recipe, local: true do |f| %>
  <div class="mb-3">
    <%= f.label :name, class: "form-label" %>
    <%= f.text_field :name, class: "form-control", autofocus: true %>
  </div>

 <div class="mb-3">
    <%= f.label :ingredients, class: "form-label" %>
    <%= f.text_area :ingredients, class: "form-control" %>
</div>

 <div class="mb-3">
  <%= f.label :instructions, class: "form-label" %>
  <%= f.text_area :instructions, class: "form-control" %>
</div>

 <div class="mb-3">
  <%= f.label :source, class: "form-label" %>
  <%= f.text_field :source_url, class: "form-control" %>
</div>

 <div class="mb-3">
  <%= f.submit %>
</div>
  
<% end %>

app/views/recipes/edit.html.erb
<h1>Editing <%= @recipe.name %></h1>
<%= render 'form' %>

app/views/recipes/index.html.erb
<h1>All Recipes</h1>
  <ul>
  <% @recipes.each do |recipe| %>
    <li><%= link_to recipe.name, recipe %>
  <% end %>
  </ul>
  <p>
    <%= link_to 'New Recipe', new_recipe_path %>
  </p>
  

app/views/recipes/new.html.erb
<h1>Create a New Recipe</h1>
<%= render 'form' %>

app/views/recipes/show.html.erb
<h1><%= @recipe.name %></h1>

<h3>Ingredients:</h3>
<p><%= simple_format(@recipe.ingredients) %></p>
  
<h3>Instructions:</h3>
<p><%= simple_format(@recipe.instructions) %></p>

<h3>Source:</h3>
<p><%= link_to @recipe.source_url, @recipe.source_url, target: :_blank, rel: :noopener %></p>
<% if current_user.admin? %>
  <p>
    <%= link_to 'Edit', edit_recipe_path(@recipe) %>
    <%= link_to 'Delete', @recipe, method: :delete, data: {
      confirm: "Are you sure you want to delete #{@recipe.name}?"
    } %>
  </p>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> alert-dismissible fade show text-center" role="alert">
    <%= message %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "Recipes", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "All Recipes", root_path, class: "nav-link" %>
        </li>
      </ul>
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          <%= link_to "Edit Account", edit_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
        <% if user_signed_in? %>
          <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-link" %>
        <% else %>
          <%= link_to "Sign In", new_user_session_path, class: "nav-link" %>
        <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>